name: Cleanup PR Deployment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Delete PR service
        run: |
          gcloud run services delete next-app-project-pr-${{ github.event.number }} \
            --region us-central1 \
            --quiet || echo "Service not found or already deleted"

      - name: Comment PR with cleanup confirmation
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 **Preview deployment cleaned up**\n\nService \`next-app-project-pr-${{ github.event.number }}\` has been deleted.`
            });
